spring:
  application:
    name: gateway
  profiles:
    #默认启动
    active: dev
  cloud:
    consul:
      discovery:
        service-name: gateway
        deregister: true
    gateway:
      routes:
        - id: login
          uri: lb://authcenter
          predicates:
            - Path=/login
        - id: wordbase
          uri: lb://wordbase
          predicates:
            - Path=/wordbase/**
          filters:
            - StripPrefix=1
        - id: test
          uri: lb://test
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
---
server:
  port: 9101
spring:
  profiles: dev
  cloud:
    consul:
      host: 192.168.2.119
      port: 8500
---
server:
  port: 8080
spring:
  profiles: test
  cloud:
    consul:
      host: 172.31.0.3
      port: 8500
---
server:
  port: 8080
spring:
  profiles: prod