spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  application:
    name: gateway
  profiles:
    #默认启动
    active: DEV
  cloud:
    consul:
      discovery:
        service-name: gateway
        deregister: true
    gateway:
      routes:
        - id: login
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: wordbase
          uri: lb://wordbase
          predicates:
            - Path=/wordbase/**
          filters:
            - StripPrefix=1
        - id: test
          uri: lb://test
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
---
server:
  port: 9100
spring:
  profiles: DEV
  cloud:
    consul:
      host: 192.168.2.12
      port: 3599
---
server:
  port: 8080
spring:
  profiles: TEST
  cloud:
    consul:
      host: 172.22.10.3
      port: 8500
---
server:
  port: 8080
spring:
  profiles: PROD
  cloud:
    consul:
      host: 172.22.10.3
      port: 8500